spring.datasource.url = jdbc:mysql://localhost:3306/food_shop
spring.datasource.username = root
spring.datasource.password = 123456

# HikariCP settings
spring.datasource.hikari.allow-pool-suspension = true
spring.datasource.hikari.connection-timeout = 30000

spring.jpa.hibernate.ddl-auto = none
#spring.jpa.hibernate.ddl-auto = create
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.hibernate.ddl-auto = create-drop

#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL55Dialect
spring.jpa.properties.hibernate.enable_lazy_load_no_trans = true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Thay YOUR_GOOGLE_API_KEY b?ng key Gemini API th?c t?
openrouter.api.key=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
openrouter.model=openai/gpt-4o-mini
google.ai.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:generateContent

# Kafka Settings
spring.kafka.bootstrap-servers=localhost:9092

# Consumer
spring.kafka.consumer.group-id=real-estate-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/





server.address=0.0.0.0
server.port=8080